classDiagram
    Animal <|-- Duck
    Animal <|-- Fish
    Animal <|-- Zebra
    Animal : +int gender
    Animal : +String gender
    Animal:  +isMammal()
    Animal: +mate()
    class Duck{
        +String beakColor
        +swim()
        +quack()
    }
    class Fish{
        .int sizeInFeet
        .catEat()
    }
    class Zebra{
        +bool is_wild
        +run()
    }